project_name: gi
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gi
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# https://goreleaser.com/customization/#Homebrew
brews:
  - tap:
      owner: uu64
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/uu64/gi
    description: A simple interactive CLI tool to create a gitignore.
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/gi", "--version"
