# This file was generated by GoReleaser. DO NOT EDIT.
class Gi < Formula
  desc "A simple interactive CLI tool to create a gitignore."
  homepage "https://github.com/uu64/gi"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/uu64/gi/releases/download/v0.2.0/gi_darwin_x86_64.tar.gz"
    sha256 "b735cb670e2cebc2aa170c5fb22e176d3ca4f92e93243949911f902df40aa458"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/uu64/gi/releases/download/v0.2.0/gi_linux_x86_64.tar.gz"
    sha256 "4282b180e02c5d2833c06925db77e54a70b2c50b5cc629339213c8a09856d665"
  end

  def install
    bin.install "gi"
  end

  test do
    system "#{bin}/gi", "--version"
  end
end
