name: ubuntu

on:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
          go vet ./...
      - name: Test
        run: |
          go test -v ./...

