name: ubuntu

on:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          make setup
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test

